# Generated by Django 4.2.3 on 2023-07-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="about",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="about_images"),
                ),
                ("descriptionESP", models.CharField(max_length=600)),
                ("descriptionENG", models.CharField(max_length=600)),
                ("ref", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
