# Generated by Django 4.2.3 on 2023-07-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images"
                    ),
                ),
                ("location", models.URLField(null=True)),
                ("duration", models.CharField(max_length=240)),
                ("description", models.CharField(max_length=510)),
                ("price", models.FloatField()),
            ],
        ),
    ]
